### ISSUE TITLE
Error in line 203 of CookieMonster.php

### ISSUE THREAD

**Issue by meyergru** [bizley/yii2-cookiemonster#1]
When setting a cookie domain, there will be an error:

yii\base\ErrorException:2] exception 'yii\base\ErrorException' with message 'preg_match() expects at least 2 parameters, 1 given' in /home/xyz/vendor/bizley/cookiemonster/src/CookieMonster.php:203

This is correct, as preg_match must have 2 parameters at least. I believe the 2nd parameter should be $value.

**Comment by bizley** [comment]
Thanks!

**Comment by meyergru** [comment]
Great work. But by your refactoring of parameters from 'cookie' into 'content', the README.md becomes wrong, e.g. the "domain" parameter must be moved now.

**Comment by bizley** [comment]
I'm not sure what are you referring to. Could you elaborate?
I'm pretty sure I have not moved parameters...

**Comment by meyergru** [comment]
+1, you are right. I just looked at the diff and saw domain now below 'content', but the @vars are above the sections... all is fine now. Thanks!
