### ISSUE TITLE
Decline button

### ISSUE THREAD

**Issue by fiSCIENCES** [bizley/yii2-cookiemonster#44]
Hello,

How can I add a decline button to go to an HTML link?

Thank you.

**Comment by bizley** [comment]
You need to set `mode` to `custom` and add `box[view]`  with path to the custom widget view that will add this button. Out of the box there is only `ok` button present.

**Comment by fiSCIENCES** [comment]
OK, do you have a sample working code for it?
Thank you.

**Comment by bizley** [comment]
No but just take the [original view](https://github.com/bizley/yii2-cookiemonster/blob/master/src/views/box.php) and add html for the extra button.

**Comment by fiSCIENCES** [comment]
OK, I added this code right after the Html::button(...) code:
`echo Html::a(
    Html::button(
        Yii::t(
            $content['category'],
            Yii::t('FileMaker','msg__cookie_notice_quit'),
            $content['buttonParams'],
            $content['language']
        ),
    ),
    'https://www.fisciences.com/conservawin/',
    ['style' => 'color:#000000;'],
);`
This code work if I add it to your box.php file, but if I try with my own view using mode and box[view], the code is generated but will never popup.
Thank you.
